[package]
name = "rclash-core-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5"
log = "0.4"
thiserror = "2"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "process", "sync"] }
reqwest = { version = "0.13", features = ["blocking", "json", "rustls-no-provider"], default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
rclash-config = { path = "../rclash-config" }
