[package]
name = "rclash"
version = "0.1.0"
edition = "2021"
description = "RClash — desktop proxy client, 100% mihomo compatible"
license = "GPL-3.0"
authors = ["RClash"]
rust-version = "1.77"

[dependencies]
eframe = { version = "0.32", features = ["default"] }
egui = "0.32"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
dirs = "5"
anyhow = "1"
reqwest = { version = "0.12", features = ["json", "rustls-tls-webpki-roots"], default-features = false }
tokio = { version = "1", features = ["rt", "rt-multi-thread", "sync"] }
rclash-config = { path = "crates/rclash-config" }
rclash-core-manager = { path = "crates/rclash-core-manager" }
rclash-sys-proxy = { path = "crates/rclash-sys-proxy" }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

[workspace]
members = ["crates/rclash-config", "crates/rclash-core-manager", "crates/rclash-sys-proxy"]
